/*
 * hconfigure.h
 *
 *  Created on: Dec 22, 2016
 *      Author: lyc
 */

#ifndef HCONFIGURE_H_
#define HCONFIGURE_H_

/* THIS FILE IS GENERATED BY SETUP: DO NOT EDIT */
#ifndef IMOD_CONFIG_INCLUDED
#define IMOD_CONFIG_INCLUDED
#define VERSION              $imod_version
#define VERSION_NAME "$imod_version_name"
#define COPYRIGHT_YEARS "$imod_copyright"




#define CTRL_STRING "$ctrl_string"
typedef char b3dByte;
typedef unsigned char b3dUByte;
typedef short int b3dInt16;
typedef unsigned short int b3dUInt16;
typedef int b3dInt32;
typedef unsigned int b3dUInt32;
typedef float b3dFloat;

#endif



#endif /* HCONFIGURE_H_ */
